var categories = [
    "Adventure Time",
    "Corgis",
    "Deal With It",
    "Facepalms",
    "Penguins",
    "Pokémon",
    "Pugs",
]
var gifs = [
    [
        "Dancing Jake.gif",
        "Dark Knight.gif",
        "Jammin Jake.gif",
    ],
    [
        "Fishing.gif",
        "Lifejacket Jump.gif",
        "Pet Me.gif",
        "Snowball.gif",
        "Swing.gif",
        "Wake Up.gif",
    ],
    [
        "Squirtle.gif",
    ],
    [
        "Beast.gif",
        "Owl.gif",
        "Wolverine.gif",
    ],
    [
        "Boss.gif",
        "Drama.gif",
        "Feets.gif",
        "Mass.gif",
        "Newspaper.gif",
        "Penguin vs Sea Lion.gif",
        "Sliding.gif",
        "Superheroes.gif",
    ],
    [
        "Adorable Stantler.gif",
        "Always Hungry.gif",
        "Baby Faces.gif",
        "Captain.gif",
        "Denied.gif",
        "Epic Flight.gif",
        "Group Photo.gif",
        "Hair Puzzle.gif",
        "High Five.gif",
        "Illiterate Chansey.gif",
        "Ketchup.gif",
        "No Idea.gif",
        "Olympics.gif",
        "Sleeping Bag.gif",
        "Squirtle Squad.gif",
        "Surfing.gif",
        "The Hat.gif",
        "There There.gif",
    ],
    [
        "Attack of the Mummy.gif",
        "Avengers.gif",
        "Awkward.gif",
        "Calm Down There.gif",
        "Chocolate Factory.gif",
        "Confused Pugs.gif",
        "Confused.gif",
        "Doting.gif",
        "Fridge.gif",
        "Hulk.gif",
        "King Pug.gif",
        "Offended Ancestors.gif",
        "Oh the Majesty.gif",
        "Party Taim.gif",
        "Pew Pug.gif",
        "Piano.gif",
        "Running Derp.gif",
        "Shopping.gif",
        "Smiling.gif",
        "So Majestic.gif",
        "The Common Pug.gif",
        "Toilet.gif",
        "WUT.gif",
        "Windshield Wipers.gif",
    ],
]
