var categories = [
    "adventure time",
    "aha",
    "awkward",
    "badawesome",
    "banhammer",
    "boom",
    "burn",
    "careful",
    "cinemagraphs",
    "clap",
    "confident",
    "contempt",
    "corgis",
    "crying",
    "dancing",
    "deal with it",
    "defused",
    "disgust",
    "distracted",
    "doge",
    "done",
    "epic",
    "excited",
    "facepalms",
    "fail",
    "goats",
    "gravity falls",
    "haters gonna",
    "he-man",
    "hiding",
    "high five",
    "mind blown",
    "no idea",
    "oh my",
    "penguins",
    "pokemon",
    "pugs",
    "smile",
    "star wars",
    "thumbs-up",
]
var gifs = [
    [
        "dancing jake.gif",
        "dark knight.gif",
        "giphy.gif",
        "jammin jake.gif",
    ],
    [
        "aha.gif",
    ],
    [
        "white guys.gif",
    ],
    [
        "chuck norris split.gif",
        "skate rope.gif",
        "split.gif",
    ],
    [
        "thor banhammer.gif",
    ],
    [
        "atomic bomb.gif",
        "booyah.gif",
        "fist bump.gif",
        "nuke.gif",
    ],
    [
        "regular show.gif",
    ],
    [
        "sand bag.gif",
    ],
    [
        "dat kickflip.gif",
        "pour.gif",
        "raining.gif",
    ],
    [
        "applause.gif",
        "bumblebee.gif",
        "clap.gif",
        "conan.gif",
    ],
    [
        "black man.gif",
        "confident.gif",
        "fox.gif",
    ],
    [
        "dwight.gif",
        "enough internet.gif",
        "max smart.gif",
        "neil degrasse tyson.gif",
        "oh please.gif",
        "simon cowel.gif",
    ],
    [
        "fishing.gif",
        "lifejacket jump.gif",
        "mind blown.gif",
        "pet me.gif",
        "snowball.gif",
        "swing.gif",
        "wake up.gif",
    ],
    [
        "bugs bunny.gif",
        "gushing.gif",
        "jim.gif",
        "obama.gif",
        "peter parker.gif",
    ],
    [
        "bane.gif",
        "batman.gif",
        "dancin.gif",
        "hammer time.gif",
        "more stomrtroopin.gif",
        "napoleon-dance.gif",
        "shufflin robot.gif",
        "stormtroopin.gif",
        "yoda.gif",
    ],
    [
        "hamster.gif",
        "money baller.gif",
        "paul rudd.gif",
        "skateboard.gif",
        "slide.gif",
        "sloth.gif",
        "squirtle.gif",
    ],
    [
        "macgyver.gif",
    ],
    [
        "depp.gif",
        "disgust.gif",
        "disgusted.gif",
        "gangsta.gif",
        "lion king.gif",
        "ted.gif",
        "uh yeah.gif",
    ],
    [
        "up.gif",
    ],
    [
        "firefox.gif",
        "space.gif",
        "work.gif",
    ],
    [
        "hand wipe.gif",
    ],
    [
        "beard slap.gif",
        "bulldozer.gif",
        "stickman adventure.gif",
        "supersnail.gif",
        "techno viking.gif",
    ],
    [
        "ace ventura.gif",
        "bboy bear.gif",
        "cookie monster.gif",
        "excited baby.gif",
        "excited kids.gif",
        "fist pump.gif",
        "fitty cent.gif",
        "giggle.gif",
        "github yissssss.gif",
        "happy dance.gif",
        "kip.gif",
        "levar burton.gif",
        "noice.gif",
        "snoop.gif",
        "super happy men.gif",
        "thumbs up.gif",
        "wooo.gif",
        "zoolander.gif",
    ],
    [
        "beast.gif",
        "owl.gif",
        "picard.gif",
        "wolverine.gif",
        "worf.gif",
    ],
    [
        "dance.gif",
        "forklift crash.gif",
        "hobbits.gif",
        "jedi dog.gif",
        "mascot.gif",
        "monday crash.gif",
        "skate party wipeout.gif",
    ],
    [
        "thirsty.gif",
    ],
    [
        "pretending.gif",
        "regrets.gif",
    ],
    [
        "lizard machine.gif",
        "moonwalking minihorse.gif",
        "power wheel.gif",
    ],
    [
        "punch.gif",
        "transform.gif",
        "unicorn.gif",
        "wall.gif",
    ],
    [
        "hiding.gif",
        "homer.gif",
    ],
    [
        "corgi.gif",
        "racoon.gif",
        "turtles.gif",
    ],
    [
        "commercial.gif",
        "jimmy.gif",
        "magic.gif",
        "mind blown.gif",
        "old spice.gif",
        "russell brand.gif",
    ],
    [
        "doge.gif",
        "driving.gif",
        "leap.gif",
        "maintenance.gif",
    ],
    [
        "austin powers.gif",
        "fresh prince.gif",
    ],
    [
        "boss.gif",
        "drama.gif",
        "feets.gif",
        "mass.gif",
        "newspaper.gif",
        "penguin vs sea lion.gif",
        "sliding.gif",
        "superheroes.gif",
    ],
    [
        "adorable stantler.gif",
        "always hungry.gif",
        "baby faces.gif",
        "camping.gif",
        "captain.gif",
        "denied.gif",
        "epic flight.gif",
        "group photo.gif",
        "hair puzzle.gif",
        "hat.gif",
        "high five.gif",
        "illiterate chansey.gif",
        "ketchup.gif",
        "no idea.gif",
        "olympics.gif",
        "squirtle squad.gif",
        "surfing.gif",
        "there there.gif",
    ],
    [
        "avengers.gif",
        "awkward.gif",
        "calm down.gif",
        "chocolate factory.gif",
        "common pug.gif",
        "confused pugs.gif",
        "confused.gif",
        "doting.gif",
        "fridge.gif",
        "hulk.gif",
        "king pug.gif",
        "mummy.gif",
        "offended ancestors.gif",
        "oh the majesty.gif",
        "party taim.gif",
        "pew pug.gif",
        "piano.gif",
        "running derp.gif",
        "shopping.gif",
        "smiling.gif",
        "so majestic.gif",
        "toilet.gif",
        "windshield wipers.gif",
        "wut.gif",
    ],
    [
        "arnold.gif",
    ],
    [
        "vader.gif",
    ],
    [
        "chinese.gif",
        "chuck norris.gif",
        "levar burton.gif",
        "suits.gif",
        "terminator.gif",
    ],
]
